name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Configuração para o Backend
      - name: Instalar dependências (Backend)
        run: |
          cd server
          npm install

      # Configuração para o Frontend
      - name: Instalar dependências (Frontend)
        run: |
          cd client
          npm install

      # Garante que o Front-end compila sem erros
      - name: Build Frontend
        run: |
          cd client
          npm run build